package com.ieltsaitutor.learning.intelligence;

public enum LearningEventType {
    PRACTICE_STARTED, QUESTION_VIEWED, ANSWER_SELECTED, ANSWER_CHANGED, ANSWER_SUBMITTED,
    QUESTION_CORRECT, QUESTION_INCORRECT, PRACTICE_COMPLETED, HINT_REQUESTED,
    EXPLANATION_REQUESTED, WRITING_SUBMITTED, WRITING_FEEDBACK_RECEIVED, SPEAKING_SUBMITTED,
    ROADMAP_ITEM_STARTED, ROADMAP_ITEM_COMPLETED
}
