spring.config.activate.on-profile=local-demo
demo.student-email=${DEMO_STUDENT_EMAIL:}
demo.student-first-name=${DEMO_STUDENT_FIRST_NAME:Demo Student}
demo.student-password=${DEMO_STUDENT_PASSWORD:}
demo.admin-email=${DEMO_ADMIN_EMAIL:}
demo.admin-first-name=${DEMO_ADMIN_FIRST_NAME:Demo Admin}
demo.admin-password=${DEMO_ADMIN_PASSWORD:}
